Added deploy plan, closes #78

diff --git a/bamboo-specs/plan-build-for-release.yaml b/bamboo-specs/plan-build-for-release.yaml
--- a/bamboo-specs/plan-build-for-release.yaml
+++ b/bamboo-specs/plan-build-for-release.yaml
@@ -16,6 +16,12 @@ stages:
       final: false
       jobs:
         - Build
+  - Tag:
+      # Temporarily tag stage is manually triggered.
+      manual: true
+      final: false
+      jobs:
+        - Tag
 
 Build:
   key: BUILD
@@ -34,6 +40,12 @@ Build:
               exit 1
             fi
 
+            # Check if the version is present in CHANGELOG.md
+            if ! grep -q "^## ${bamboo.release.version}$" CHANGELOG.md; then
+              echo "Error: Version ${bamboo.release.version} not found in CHANGELOG.md. Please update the changelog."
+              exit 1
+            fi
+
             # Build the release artifacts.
             make release
 
@@ -46,11 +58,6 @@ Build:
         scope: RESULT
         namespace: inject
         description: Inject Bamboo variables
-    - any-task:
-        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
-        configuration:
-          selectedRepository: defaultRepository
-          tagName: v${bamboo.release.version}
   artifacts:
     - name: ConverterTool
       location: ./build/release
@@ -65,6 +72,21 @@ Build:
   requirements:
     - image: registry.int.agrd.dev/macos/sequoia-build-agent-xcode16.3:latest
     - ephemeral
+
+Tag:
+  key: TAG
+  docker:
+    image: adguard/node-ssh:22.14--0
+  tasks:
+    - checkout:
+        force-clean-build: "true"
+    - any-task:
+        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
+        configuration:
+          selectedRepository: defaultRepository
+          tagName: v${bamboo.inject.version}
+  requirements:
+    - adg-docker: "true"
 
 branches:
   create: manually
